name: Deploy Boter

on:
  push:
    branches:
      - master  # или main, если у вас основная ветка называется main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Отправка обновления на VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/Boter
            git pull
            systemctl restart Boter
